# Generated by Django 4.2.3 on 2023-09-07 20:07

from django.db import migrations, models
import news.validators


class Migration(migrations.Migration):
    dependencies = [
        ("news", "0002_news"),
    ]

    operations = [
        migrations.AlterField(
            model_name="news",
            name="created_at",
            field=models.DateField(validators=[news.validators.validate_date]),
        ),
        migrations.AlterField(
            model_name="news",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="img/"),
        ),
        migrations.AlterField(
            model_name="news",
            name="title",
            field=models.CharField(
                max_length=200,
                validators=[
                    news.validators.validate_fields,
                    news.validators.validate_title,
                ],
            ),
        ),
    ]
